# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"

[version]
current = "0.2.0"

regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<prelease>\-\w+\.\d+)?
  '''

[git]
message_template = "Release {new_version}"
tag_template = "v{new_version}"

[[before_commit]]
# Updates self-dependency in Cargo.lock
name = "cargo check"
cmd = "cargo check && git add Cargo.lock"

[[file]]
src = "Cargo.toml"
