name: CI

on:
  push:

jobs:
  test:
    name: test (${{ matrix.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: no_std-safe
            opts: "--no-default-features"
          - name: no_std-unsafe
            opts: "--features unsafe"
          - name: std-safe
            opts: "--features std"
          - name: std-unsafe
            opts: "--features std,unsafe"
          - name: repl-safe
            opts: "--features repl"
          - name: repl-unsafe
            opts: "--features repl,unsafe"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: cargo test ${{ matrix.opts }}
